site_name: Baba Bear Website
site_url: https://dinoandstef.com

theme:
  name: material
  font:
    text: Roboto # This keeps your buttons looking exactly as they do now
    code: Roboto Mono
  icon:
    logo: material/heart
  features:
    - search.suggest # Keep this line if you ever turn search back on
  # Add this empty dictionary to override and disable the search plugin
plugins: [] 

# This navigation menu tells MkDocs which pages exist
nav:
  - Home: index.md
  - Feed: feed.md
  - Snack: snack.md
  - Meal: meal.md
  - Breakfast: breakfast.md
  - Lunch: lunch.md
  - Dinner: dinner.md
    

# These extensions allow us to use buttons and click-to-reveal blocks
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css