site_name: Baba Bear Website
site_url: https://dinoandstef.com

theme:
  name: material

# This navigation menu tells MkDocs which pages exist
nav:
  - Home: index.md
  - Feed: feed.md
  - Snack: snack.md
  - Meal: meal.md
  - Breakfast: breakfast.md
  - Lunch: lunch.md
    

# These extensions allow us to use buttons and click-to-reveal blocks
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

extra_css:
  - stylesheets/extra.css